# Generated by Django 3.1.7 on 2021-03-27 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210327_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateOfBirth',
        ),
        migrations.AddField(
            model_name='student',
            name='dateOfEnrol',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Enrolment'),
            preserve_default=False,
        ),
    ]
